import Layout from "@/components/reuse/layout";
import React, { useState, useContext } from "react";
import AddIcon from "@mui/icons-material/Add";
import MinusIcon from "@mui/icons-material/Remove";
import {
  Accordion,
  AccordionSummary,
  Typography,
  AccordionDetails,
} from "@mui/material";
import CustomAds from "@/components/customads";
import Head from "next/head";
import ContactStyles from "../styles/Contact.module.scss";
import Image from "next/image";
import Location from "../public/icon/location.svg";
import Email from "../public/icon/email.svg";
import Call from "../public/icon/call.svg";
import Facebook from "../public/icon/facebookp.svg";
import Twitter from "../public/icon/twitterp.svg";
import Instagram from "../public/icon/instagramp.svg";
import { VerifyUserContext } from "@/context/verifyUserContext";
import Linkedin from "../public/icon/linkedin.svg";
import ContactLine from "../public/img/contactline.png";
import axios from "axios";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Link from "next/link";

const Contact = () => {
  const { faqs } = useContext(VerifyUserContext);
  const [expanded, setExpanded] = useState(false);
  const [formData, setFormData] = useState({
    email: "",
    firstName: "",
    lastName: "",
    message: "",
  });

  const handleInputChange = (event) => {
    setFormData({ ...formData, [event.target.name]: event.target.value });
  };

  const handleChange = (id) => (event, isExpanded) => {
    setExpanded(isExpanded ? id : false);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    try {
      const response = await axios.post(
        `${process.env.BASE_URL}/api/contactus`,
        formData
      );
      if (response.status === 201) {
        toast.success("Message sent successfully!");
        setFormData({
          email: "",
          firstName: "",
          lastName: "",
          message: "",
        });
      }
    } catch (error) {
      toast.error("Error submitting form. Please try again.");
    }
  };

  return (
    <div>
      <Head>
        <title>Contact Us || Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          property="og:url"
          content="https://africanproverbs.com/contact/"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout pageTitle="Contact Us" pageLink="Contact">
          <div className={ContactStyles["contact-container"]}>
            <div className={ContactStyles["contact--top-container"]}>
              <div className={ContactStyles["contact-left"]}>
                <h1>Get In Touch With Our Team</h1>
                <p className={ContactStyles["contact-desc"]}>
                  We value feedback from our visitors and are always looking for
                  ways to improve our website and resources
                </p>
                <span>
                  <Image
                    width={"100%"}
                    height={"100%"}
                    src={Location}
                    alt={"Location Icon"}
                  />
                  <p>118b, Ilupeju way, Dolphin estate, Ikoyi lagos</p>
                </span>
                <span>
                  <Image
                    width={"100%"}
                    height={"100%"}
                    src={Email}
                    alt={"Email Icon"}
                  />
                  <p>contact@calmglobal.com</p>
                </span>
                <span>
                  <Image
                    width={"100%"}
                    height={"100%"}
                    src={Call}
                    alt={"Call Icon"}
                  />
                  <p>+2348107536218</p>
                </span>

                <Image
                  width={"100%"}
                  height={"100%"}
                  className={ContactStyles["contact-line"]}
                  src={ContactLine}
                  alt={"Horizontal Line"}
                />

                <div className={ContactStyles["socials-background"]}>
                  <h2>Connect with us</h2>

                  <span className={ContactStyles.socials}>
                    <div className={ContactStyles["social-image-background"]}>
                      <Image
                        width={"100%"}
                        height={"100%"}
                        src={Facebook}
                        alt={"Facebook Icon"}
                      />
                    </div>
                    <div className={ContactStyles["social-image-background"]}>
                      <Image
                        src={Twitter}
                        width={"100%"}
                        height={"100%"}
                        alt={"Twitter Icon"}
                      />
                    </div>
                    <div className={ContactStyles["social-image-background"]}>
                      <Link
                        href={
                          "https://instagram.com/calmglobal_it?igshid=YmMyMTA2M2Y="
                        }
                      >
                        <Image
                          src={Instagram}
                          width={"100%"}
                          height={"100%"}
                          alt={"Instagram Icon"}
                        />
                      </Link>
                    </div>
                    <div className={ContactStyles["social-image-background"]}>
                      <Link
                        href={
                          "https://www.linkedin.com/company/calm-global-information-technologies-ltd/"
                        }
                      >
                        <Image
                          src={Linkedin}
                          width={"100%"}
                          height={"100%"}
                          alt={"Linkedin Icon"}
                        />
                      </Link>
                    </div>
                  </span>
                </div>
              </div>

              <div className={ContactStyles["contact-right"]}>
                <form onSubmit={handleSubmit}>
                  <div className={ContactStyles["contact-form"]}>
                    <div className={ContactStyles["contact-form-names"]}>
                      <input
                        value={formData.firstName}
                        onChange={handleInputChange}
                        name="firstName"
                        type="text"
                        placeholder="First Name"
                      />
                      <input
                        value={formData.lastName}
                        onChange={handleInputChange}
                        name="lastName"
                        type="text"
                        placeholder="Last Name"
                      />
                    </div>

                    <input
                      value={formData.email}
                      onChange={handleInputChange}
                      name="email"
                      type="email"
                      placeholder="Email"
                    />
                  </div>

                  <textarea
                    value={formData.message}
                    onChange={handleInputChange}
                    name="message"
                    id="message"
                    // cols="30"
                    // rows="10"
                    placeholder="Message"
                  ></textarea>

                  <button type="submit">Send Message</button>
                </form>
              </div>
            </div>
            <CustomAds />
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div className={ContactStyles["freq-container"]}>
                <h1>Frequently Asked Questions</h1>
                <div className={ContactStyles["freq-tab"]}>
                  {faqs?.map((faq) => (
                    <Accordion
                      key={faq.id}
                      expanded={expanded === faq.id}
                      onChange={handleChange(faq.id)}
                      style={{
                        borderRadius: "17.802px",
                        background: "#FFF",
                        boxShadow:
                          "0px 5.5631px 17.80192px 0px rgba(8, 15, 52, 0.06)",
                        padding: "1rem",
                      }}
                    >
                      <AccordionSummary
                        expandIcon={
                          expanded === faq.id ? (
                            <MinusIcon
                              style={{
                                borderRadius: "8.901px",
                                background: "#121212",
                                color: "#fff",
                              }}
                            />
                          ) : (
                            <AddIcon
                              style={{
                                borderRadius: "8.901px",
                                background: "#F7F7FF",
                                color: "#000",
                              }}
                            />
                          )
                        }
                        aria-controls={`${faq.id}-content`}
                        id={`${faq.id}-header`}
                      >
                        <Typography
                          sx={{
                            color: "#121212",
                            fontFamily: "Mulish",
                            fontSize: "20px",
                            fontWeight: 500,
                          }}
                        >
                          {faq.question}
                        </Typography>
                      </AccordionSummary>
                      <AccordionDetails>
                        <Typography
                          sx={{
                            color: "#575757",
                            fontFamily: "Mulish",
                            fontSize: "18px",
                            fontStyle: "normal",
                            fontWeight: 400,
                          }}
                        >
                          {faq.answer}
                        </Typography>
                      </AccordionDetails>
                    </Accordion>
                  ))}
                </div>
              </div>
              <div className={ContactStyles["map-container"]}></div>
            </div>
          </div>
        </Layout>

      
      </main>
    </div>
  );
};

export default Contact;
